# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/19896/Repellion_Game/Repellion_Game.cache/wt [current_project]
set_property parent.project_path C:/Users/19896/Repellion_Game/Repellion_Game.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths c:/Users/19896/Repellion_Game/hdmi_tx_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/19896/Repellion_Game/Repellion_Game.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/19896/Repellion_Game/MainCharacter.coe
add_files C:/Users/19896/Repellion_Game/Enemy.coe
add_files C:/Users/19896/Repellion_Game/bullet.coe
add_files c:/Users/19896/Repellion_Game/Nums_32x32.coe
add_files c:/Users/19896/Repellion_Game/Score_Chars.coe
read_vhdl -library xil_defaultlib {
  C:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/new/Char_Select.vhd
  C:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/new/Enemy.vhd
  C:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/new/Enemy_lfsr.vhd
  C:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/new/Gen_Char.vhd
  C:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/new/MY_IMAGE_DRIVER.vhd
  C:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/new/UART_Receive_Data.vhd
  C:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/new/bullet.vhd
  C:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/new/merge_display.vhd
  C:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/new/new_level_logic.vhd
  C:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/new/static_background.vhd
  C:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/new/vga_controller_640_60.vhd
  C:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/new/VGA_to_HDMI.vhd
}
read_ip -quiet C:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/ip/hdmi_tx_0/hdmi_tx_0.xci

read_ip -quiet C:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet C:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet C:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/ip/bullet_rom/bullet_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/ip/bullet_rom/bullet_rom_ooc.xdc]

read_ip -quiet c:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all c:/Users/19896/Repellion_Game/Repellion_Game.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/19896/Repellion_Game/Repellion_Game.srcs/constrs_1/new/vga_pins.xdc
set_property used_in_implementation false [get_files C:/Users/19896/Repellion_Game/Repellion_Game.srcs/constrs_1/new/vga_pins.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top VGA_To_HDMI -part xc7s50csga324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef VGA_To_HDMI.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file VGA_To_HDMI_utilization_synth.rpt -pb VGA_To_HDMI_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
